# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 248f3442dbf4b8b9db260f9c38177745d2167efbce0af00b58bfb236b1deabe06169f112103ed05a5b8d5a41fdb21c5252e808d214885699fcb64049bd020ebf

test:
  secret_key_base: 2244afce4441a40ef3809e2ab98f0c09a5259431780e44609ee6615b42b0a0fb38a38e6bccbc55bdf955045cf6ca3e4a65f5d3d49bdab8b629b4e018036a689a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
